"""initial schema

Revision ID: 3c12f4aac8fb
Revises: 
Create Date: 2026-05-09 23:26:49.870813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c12f4aac8fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ielts_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('target_score', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ielts_exams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['ielts_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ielts_sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('time_limit_s', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['ielts_exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ielts_exam_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('current_section_id', sa.String(length=36), nullable=True),
    sa.Column('time_remaining_s', sa.Integer(), nullable=True),
    sa.Column('audio_played_at', sa.DateTime(), nullable=True),
    sa.Column('focus_lost_events', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['current_section_id'], ['ielts_sections.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['ielts_exams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ielts_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ielts_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.JSON(), nullable=True),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['ielts_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ielts_annotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('passage_group_id', sa.String(length=36), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('selected_text', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ielts_exam_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ielts_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('auto_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['ielts_questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['ielts_exam_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_ielts_answer_session_question')
    )
    op.create_table('ielts_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('section_type', sa.String(length=20), nullable=False),
    sa.Column('scaled_score', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('raw_score', sa.Integer(), nullable=True),
    sa.Column('ai_scores', sa.JSON(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('sentence_highlights', sa.JSON(), nullable=True),
    sa.Column('teacher_override_score', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('teacher_feedback', sa.Text(), nullable=True),
    sa.Column('teacher_feedback_audio_key', sa.String(length=512), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ielts_exam_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'section_type', name='uq_ielts_score_session_section')
    )
    op.create_table('ielts_speaking_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('part_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('audio_file_key', sa.String(length=512), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ielts_exam_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ielts_writing_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('task_number', sa.Integer(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ielts_exam_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'task_number', name='uq_ielts_writing_session_task')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ielts_writing_responses')
    op.drop_table('ielts_speaking_responses')
    op.drop_table('ielts_scores')
    op.drop_table('ielts_answers')
    op.drop_table('ielts_annotations')
    op.drop_table('ielts_questions')
    op.drop_table('ielts_exam_sessions')
    op.drop_table('ielts_sections')
    op.drop_table('ielts_exams')
    op.drop_table('ielts_users')
    # ### end Alembic commands ###
