"""add listening_parts_played to exam_sessions

Revision ID: 55c01aa4d05b
Revises: 3c12f4aac8fb
Create Date: 2026-05-11 21:18:13.532718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c01aa4d05b'
down_revision = '3c12f4aac8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ielts_exam_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listening_parts_played', sa.JSON(), nullable=True, server_default='[]'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ielts_exam_sessions', schema=None) as batch_op:
        batch_op.drop_column('listening_parts_played')

    # ### end Alembic commands ###
