"""add overall_band_snapshot to student_reports

Revision ID: b5106b9b44da
Revises: d8a381d14e19
Create Date: 2026-05-16 12:54:42.763207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5106b9b44da'
down_revision = 'd8a381d14e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ielts_student_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_band_snapshot', sa.Numeric(precision=5, scale=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ielts_student_reports', schema=None) as batch_op:
        batch_op.drop_column('overall_band_snapshot')

    # ### end Alembic commands ###
