"""add student_reports table

Revision ID: d8a381d14e19
Revises: 55c01aa4d05b
Create Date: 2026-05-16 11:52:16.468287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a381d14e19'
down_revision = '55c01aa4d05b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ielts_student_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('generated_by', sa.String(length=36), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('selections', sa.JSON(), nullable=False),
    sa.Column('target_band_snapshot', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('report_markdown', sa.Text(), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['ielts_users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['ielts_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ielts_student_reports')
    # ### end Alembic commands ###
